In [2]:
import numpy as np

In [9]:
x=np.array([1., 2., 3., 4., 5.])

print(x)
x = x.flatten()
print(x)#?????



[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]


In [10]:
def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    y = AND(s1, s2)
    return y;

a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
print(np.ndim(a))
print(a.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
